### ISSUE TITLE
Pete's Pod

### ISSUE THREAD

**Issue by romebell** [SEI-ATL/UNIT_2#20]
### Add your link to the ISSUE that you create here. Be sure to assign your Pod Leader

**Comment by anonyymous1** [comment]
Looked into searching with an array, thats a no go. Also, did research on the restrictions of what you can store to your DB and it seems like the creator doesn't mind what you do with it. My next questions is does it makes sense to store everything for a persons favorite so that it doesn't request from the API a lot like we discussed OR should I store the main attributes like I did below?

I also have a question about how my join table should look:

![Screen Shot 2020-11-30 at 11 30 19 AM](https://user-images.githubusercontent.com/71801837/100636779-1200f000-3300-11eb-8a3b-7c3be0480614.png)

![Screen Shot 2020-11-30 at 11 49 57 AM](https://user-images.githubusercontent.com/71801837/100638581-31008180-3302-11eb-84c4-a1ebbe6ceb44.png)

**Comment by pmacaluso3** [comment]
Re: what to store, I'd say store everything you think you could want to display, erring on the side of grabbing too much. Re: how the favorites table should look, you definitely want it (and all tables) to have a PK id field
